* 个人简介
* 个人经历
** 大学经历
  大学四年在实验室呆三年，大一时跟着学长学习c语言和51单片机，暑假期间并留校参加电子设计大赛培训;在大二时被选拔参加飞思卡尔智能车大赛;在大三时购买囯嵌的嵌入式Linux视频，开始了自学的生涯，在那之后我就告别了Windows系统；学习各种命令，脚本，arm,Linux应用编程,linux移植及驱动编写；在大四时获得江苏润和公司的智能终端部门的实习机会，部门主要业务是Android手机系统的开发，我主要研究的方向是kernel层；在润和中学习到很多东西！
   + 大一
     参加科学与技术创新协会，在社团中接触了实验室，就跟着学长自学c语言、51单片机以及电路相关的知识，从此我就开始了我的实验室生涯。
   + 大二
     由于自己在实验室的突出表现，成功获取参加飞思卡尔智能车大赛的资格。并在比赛时接触了arm,摄像头，操作系统相关的概念。遗憾的是成绩并不理想。
   + 大三
     由于自己喜欢逛论坛和博客，在一次偶然的机会我发现了linux这个玩具，发现这是个有意思的东西，我就放弃了大三继续参加飞思卡尔的比赛,从网上买了国嵌的视频和友善科技的tiny6410开发板，从此就踏入了一个人自学嵌入式linux的道路上；现在回想起那段学习经历，内心有一种恐惧。
   + 大四
     在大三学习嵌入式linux过程中，我认识了润和公司的员工.在他的推荐下，我获取了润和实习生的机会；我大三放假后，在2016。07.1我在润和入职，在这里我就开始了我的实习经历；幸运的是我所从事的工作是android的kernel层，kernel是linux,这和我研究的方向一致，我和父母商量，让他们和学校沟通下，我大四就没上，就留在润和实习。
** 工作经历
*** 2016.07.1到润和实习至今
    1. 负责解决android中的SElinux问题。
    2. 负责android中的lk(bootloader)和kernel中的驱动
    3. 负责android的高通平台power功耗分析，排查问题所在。
** 业余生活
   喜欢运动，周六周日到三江学院大羽毛球
   在21点左右健身
   工作之余，喜欢折腾自己的笔记本，折腾linux的服务器配置以及个人工作环境的配置。
* 项目
** idol4
   + 项目内容：
     TCL要求把idol4手机系统从Android 6升级到Android 7.1.1
   + 手机硬件
     CPU:msm8952
     TOUCH:ft5436
     Memory:2G RAM + 32G ROM
     项目周期：2016.07.3 -- 2017.1.3
   + 负责内容
     负责解决SElinux问题。
     负责lk(bootloader)和kernel中的led（flash,torch,RGB,wled）移植,并熟悉led驱动框架和高通led平台驱动框架及对应设备树。
     负责power功耗分析，排查问题所在。
     抓取log，复现bug,手机系统刷机。
   + 贡献
   + 收获
     掌握了gpio子系统,pinctrl子系统,led子系统,input子系统,对于debug,proc,sys文件系统理解的更深入。掌握了根据/sys/文件系统中的设备节点和设备树中的节点，定位源代码的位置
     掌握了kernel内核日志辅助调试能力(/proc/kmsg)和dynamic-debug
     lcd
     led
     wled
     touch
     keyboard
** gflip2
   + 项目内容：
     TCL的一个功能手机，用的是kaios系统.
   + 手机硬件
     CPU:msm8952
     lcd:st7789h2 st7735s
     keyboard:sn7326
     Memory:1G RAM + 8G ROM
     项目周期：2017.01.8 -- 2017.6.5
   + 负责内容
     负责解决SElinux问题。
     负责lk(bootloader)和kernel中的led（flash,torch,RGB,wled）移植,并熟悉led驱动框架和高通led平台驱动框架及对应设备树。
     负责lk(bootloader)和kernel中的input子系统中的keyboard,key以及添加debug调试信息节点。
     负责在debug文件系统中添加调试GPIO引脚状态的节点。
     负责power功耗分析，排查问题所在。
     抓取log，复现bug,手机系统刷机。
     led移植（flash,torch,RGB,wled）
     lcd
     led
     wled
     keyboard
   + 贡献
   + 收获
** Appassionato
   + 项目内容：
     TCL手机项目系统Android 7.1.2
     项目周期：2017.06.1 -- 至今
   + 手机硬件
     CPU:msm8996
     TOUCH:ftm3bd54c
     Memory:6G RAM + 128G ROM
   + 负责内容
     负责解决SElinux问题。
     负责lk(bootloader)和kernel中的led（flash,torch,RGB,wled）移植,并熟悉led驱动框架和高通led平台驱动框架及对应设备树。
     负责power功耗分析，排查问题所在。
     抓取log，复现bug,手机系统刷机。
     负责功能机矩阵按键(sn7326)驱动的移植
     led
     led,wled,touch,keyboard,bootloader驱动的编写移植。
     power调试分析
   + 贡献
   + 收获
* 工作技能
  1. 熟悉高通平台,stm32,S3C6410,exynos4412
  2. 掌握linux系统,可以完成常见服务器(ftp/sftp/mnt/tftp/ssh/vnc/vpn等)的搭建及环境配置。
  3. 掌握bootloader(u-boot,lk),linux，rootfs移植及制作。
  4. 掌握linux调试工具,ftrace/printk/Dynamic_debug/
  5. 掌握led,input,sensors,i2c,spi,input,debugfs,procfs,sysfs,设备树等子系统的使用
  6. 熟悉android源码及编译及常用工具。
  7. 掌握power功耗调试能力
* 自我评价
  1. 喜欢
* 个人优点
  1. 个人电脑使用的是fedora系统,下班之后喜欢折腾电脑玩，在这个过程中，我学会了ftp/sftp/mnt/tftp/ssh/vnc/vpn/等等服务器的搭建和配置，在这个过程中我掌握了dotconfig思想，这使得我配置系统工作环境更方便，个人配置脚本见[[https://github.com/wildbooks/dotconfig][dotconfig]]
  2. 喜欢看简书和博客，每当有所思，我都会写下一些笔记，本人笔记托管在github下[[https://github.com/wildbooks/StudyNotes][StudyNotes]]笔记写的比较随意，调理不太清晰，本笔记从2015.9(大三开学时)开始编写一直维护到现在
  3. 健身狂人，健身使我身体以及心理更加健康，这样可以使我的工作状态更加愉悦更加高效，可以让我一直维持着积极的工作态度。
  4. 善于使用github,google,baidu搜索引擎，用这些工具我发现了spaceemacs、SpaceVim、oh-my-zsh、oh-my-fish、musicbox等等好玩的工具，这对我的工作帮助是蛮大的.
* github
** StudyNotes
   https://github.com/wildbooks/StudyNotes
** dotconfig
   https://github.com/wildbooks/dotconfig
* 培训经历
  培训机构：国嵌嵌入式培训中心
  培训周期:2015.9~2016.7
  + 基础理论
    C语言基础补习
    Linux操作系统使用
    C语言高级编程
    数据结构及经典算法
    Java基础补习
    Java高级编程
  + 应用核心课程
    文件I/O
    Linux库的制作和使用
    Linux开发程序设计
    Linux网络编程
    数据库开发
    Linux综合案例
    Android应用开发基础
  + 底层开发核心课程
    ARM处理器编程
    ARM硬件接口编程
    物联网基础
    Linux系统移植
    Linux内核开发
    Linux驱动开发
    Android移植开发
  + 项目实战
    基于WiFi的智能小车开发
    仓储物联网系统开发
    基于MEMS的四旋翼飞行器开发
    便携式智能医疗系统开发
    智能农业系统开发
    智能家居+VR系统开发
