* 个人简介
* 个人经历
** 大学经历
   + 大一
     参加科学与技术创新协会，在社团中接触了实验室，就跟着学长自学c语言、51单片机以及电路相关的知识，从此我在实验室一发不可收拾。
   + 大二
     由于自己在实验室的突出表现，成功获取参加飞思卡尔智能车大赛的资格。遗憾的是成绩并不理想。
   + 大三
     由于自己喜欢逛论坛和博客，在一次偶然的机会我发现了linux这个玩具，发现这是个有意思的东西，我就放弃了大三继续参加飞思卡尔的比赛,从网上买了国嵌的视频和友善科技的tiny6410开发板，从此就踏入了一个人自学嵌入式linux的道路上；现在回想起那段学习经历，内心有一种恐惧。
   + 大四
     在大三学习嵌入式linux过程中，我认识了润和公司的员工.在他的推荐下，我获取了润和实习生的机会；我大三放假后，在2016。07.1我在润和入职，在这里我就开始了我的实习经历；幸运的是我所从事的工作是android的kernel层，kernel是linux,这和我研究的方向一致，我和父母商量，让他们和学校沟通下，我大四就没上，就留在润和实习。
** 工作经历
   2016.07.1到润和实习至今
** 业余生活
   工作之余，喜欢折腾自己的笔记本，
* 项目
** idol4
   + 项目内容：
     TCL要求把idol4手机系统从Android 6升级到Android 7.1.1
   + 手机硬件
     CPU:msm8952
     TOUCH:
     Memory:
     项目周期：2016.07.3 -- 2017.1.3
   + 负责内容
     负责解决SElinux问题。
     熟悉linux的led驱动框架和高通平台的led驱动框架及对应的设备树。
     解决idol4中的bootloader和内核中中的按键问题。
     解决idol4手机背光问题
     抓取log，复现bug
     在这期间
   + 收获
     掌握了gpio子系统,pinctrl子系统,led子系统,input子系统,对于debug,proc,sys文件系统理解的更深入。掌握了根据/sys/文件系统中的设备节点和设备树中的节点，定位源代码的位置
     掌握了kernel内核日志辅助调试能力(/proc/kmsg)和dynamic-debug
     lcd
     led
     wled
     touch
     keyboard
** gflip2
   + 项目内容：
     TCL要求把idol4手机系统从Android 6升级到Android 7.1.1
     TCL的一个功能手机，用的是kaios系统
   + 手机硬件
     CPU:msm8952
     TOUCH:
     Memory:
     项目周期：2017.01.8 -- 2017.6.5
   + 负责内容
     负责功能机矩阵按键(sn7326)驱动的移植
     lcd
     led
     wled
     keyboard
** Appassionato
   + 项目内容：
     TCL手机项目系统Android 7.1.2
     项目周期：2017.06.1 -- 至今
   + 手机硬件
     CPU:msm8996
     TOUCH:ftm3bd54c
     Memory:6G RAM + 128G ROM
   + 负责内容
     led,wled,touch,keyboard,bootloader驱动的编写移植。
     power调试分析
* 自我评价
  1. 喜欢
* 个人优点
  1. 个人电脑使用的是fedora系统,下班之后喜欢折腾电脑玩，在这个过程中，我学会了ftp/sftp/mnt/tftp/ssh/vnc/vpn/等等服务器的搭建和配置，在这个过程中我掌握了dotconfig思想，这使得我配置系统工作环境更方便，个人配置脚本见[[https://github.com/wildbooks/dotconfig][dotconfig]]
  2. 喜欢看简书和博客，每当有所思，我都会写下一些笔记，本人笔记托管在github下[[https://github.com/wildbooks/StudyNotes][StudyNotes]]笔记写的比较随意，调理不太清晰，本笔记从2015.9(大三开学时)开始编写一直维护到现在
  3. 健身狂人，健身使我身体以及心理更加健康，这样可以使我的工作状态更加愉悦更加高效，可以让我一直维持着积极的工作态度。
  4. 善于使用github,google,baidu搜索引擎，用这些工具我发现了spaceemacs、SpaceVim、oh-my-zsh、oh-my-fish、musicbox等等好玩的工具，这对我的工作帮助是蛮大的.
